### ISSUE TITLE
Именование устройства

### ISSUE THREAD

**Issue by bublikOff** [dentra/esphome-ewh#1]
Формируется устройство типа "climate.esphome_elx_ewh_100climate"  ...  где "elx_ewh_100" имя при компиляции прошивки.
А вот "climate" в конце названия немного лишнее ... можно убрать? Оно и так понятно что climate ... в начале же есть "climate."

**Comment by dentra** [comment]
к сожалению, не совсем понял, где формируется, в HA? что указано в substitutions.name? какой версией esphome собираете?

с настройками по-умолчанию (substitutions.name="Water Heater") в HA сущность будет называться просто "climate.water_heater"...

**Comment by bublikOff** [comment]
Дошли руки привести некоторые вещи в порядок в HA.
И обратил внимание на то как бойлер проваливается в HA  и увидел такую картину https://ibb.co/JBfDhJH
Видим например BST автоматом провалился в систему как switch.bst или button.restart ... т.е. они совсем без префиксов
а климат наоборот с избытком и с префиксом и постфиксом climate.esphome_elx_ewh_100climate
где постфикс на конце излишний 
PS
2022.4.2
PS 2
Хотелось бы видеть что то типа 
switch.esphome_elx_ewh_100_bst
button.esphome_elx_ewh_100_restart

**Comment by dentra** [comment]
Покажите плиз конфигурацию из которой Вы собираете прошивку.

2022.4.2 - это версия HA, как я понимаю, а какая версия ESPHome?

**Comment by bublikOff** [comment]
1) HA 2022.4.2
2) Версия ESP Home: 2022.2.4
3) Конфиг конфы

```
substitutions:
  # main prefix for all entities
  name: ""

  # name of your node
  node_name: "elx-ewh-100"

  # use "esp12e" for iot-uni-dongle, "esp8285" for coolrf-heatstick, or your own if you know it
  board: "esp12e"

  # time platform: "sntp" or "homeassistant"
  time_platform: "sntp"

  # SSID of your wifi
  wifi_ssid: !secret wifi_ssid

  # password of your wifi
  wifi_password: !secret wifi_password

  # password for fallback wifi hotspot
  #wifi_ap_password: !secret wifi_ap_password

  # version of ewh
  ewh_version: "2022.1.0"

# Set CPU frequency to 160MHz for ESP12F
esphome:

  # ESP12F CPU frequency
  platformio_options:
    board_build.f_cpu: 160000000L

wifi:
  ap:
    ssid: "ELX100"
    password: "12345678"

# please do not change packeages order it is very important, just comment/uncomment
packages:

  # required package, do not comment
  ewh: github://dentra/esphome-ewh/ewh-pkg-ewh.yaml@$ewh_version

  ## optional package, uncomment next line to enable additional diagnostic clock sensor
  # clock: github://dentra/esphome-ewh/ewh-pkg-clock.yaml@$ewh_version

  ## optional package, uncomment next line to enable additional diagnostic timer sensor
  # timer: github://dentra/esphome-ewh/ewh-pkg-timer.yaml@$ewh_version

  ## optional package, uncomment next line to enable standalone web ui
  web: github://dentra/esphome-ewh/ewh-pkg-web.yaml@$ewh_version

  ## optional package, uncomment next line to enable experimental cloud support
  #cloud: github://dentra/esphome-ewh/ewh-pkg-cloud.yaml@$ewh_version

  # required package, do not comment
  core: github://dentra/esphome-ewh/ewh-pkg-core.yaml@$ewh_version

```
