### ISSUE TITLE
Cyclic reboot of the s3 dongle after flashing

### ISSUE THREAD

**Issue by psarts** [dentra/esphome-ewh#11]
After flashing using ESPHome version 2023.12 and the config from the example, s3 dongle starts to reboot cyclically. An error appears in the esp flasher logs: "[11: 27: 13]invalid header: 0xffffffff".
Here is the configuration I used:

```
substitutions:
  friendly_name: "Water Heater"
  node_name: "water-heater"
  board: "esp32-s3-devkitc-1"
  time_platform: "sntp"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_ap_password: !secret wifi_ap_password
  tx_pin: GPIO19
  rx_pin: GPIO20 
packages:
  remote:
    url: https://github.com/dentra/esphome-ewh
    ref: master 
    files:
      - packages/uptime.yaml
      - packages/restart.yaml
      - packages/base.yaml
      - packages/esp32.yaml
time:
  platform: sntp

api:
  encryption:
    key: "ХХХ"

ota:
  password: "ХХХ"

  ssid: $wifi_ssid
  password: $wifi_password

logger:
uart:
  tx_pin: $tx_pin
  rx_pin: $rx_pin
  baud_rate: 9600

vport:
  - platform: ewh

climate:
  - platform: ewh
    id: whc
    name: None 
    bst:
      name: "BST"
```
